const data = {
  centerList: [
    {
      _id: "62e913e9f9efad001d8f473e",
      gymName: "을지로 펄스핏 피트니스",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1825e75c7082a576a4/4K8gHYEb5rWJtJKJpHwCnL8V5xTn6yNPKGD5LcYzAx9D.jpg",
      address: "서울 중구 을지로1가",
      location: [126.9795156, 37.5657387],
      review: {
        rate: 4.95,
        count: 38,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "6a006278-43d4-4e82-a99a-527b4fe8d1d3",
        productId: "ad44f1f4-d70f-4aa1-bbb8-699f22df49fa",
        productName: "헬스 회원권",
        defaultPrice: 468000,
        dagymPrice: 468000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스", "P.T"],
      program: {
        free: "",
      },
      service: {
        free: "유료주차 가능",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: 1,
      isSportsFacilityCertified: true,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "6a44b59bdd9e349a944a7ae6",
      gymName: "시청 짐마스터헬스PT",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/d6ce6b76-a946-453a-afc4-b465defc2255/1782887829121_676d89af-9751-40ab-9c41-3f552aafbd68.jpg",
      address: "서울 중구 다동",
      location: [126.9803688, 37.5671421],
      review: {
        rate: 0,
        count: 0,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "834503c4-fe81-4144-a6da-ec20d6d4e8ae",
        productId: "838fb94a-9b99-4cc8-9e13-879130c45289",
        productName: "🔥선착순🔥헬스 회원권",
        defaultPrice: 396000,
        dagymPrice: 319000,
        dagymPriceRemainingCount: 3,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["1:1P.T", "헬스"],
      program: {
        free: "",
      },
      service: {
        free: "",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "6321454882a1c2001d14e202",
      gymName: "종로 스포짐",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/e666ba94-0fbd-4ce6-b603-f4743fd7fddc/d93eab930d4b4dc8af949bb57fa59567.jpg",
      address: "서울 종로구 서린동",
      location: [126.9813088, 37.5693294],
      review: {
        rate: 4.82,
        count: 22,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "a913cee4-0dd6-4bde-8cb0-40eec7c62fed",
        productId: "fd448b74-acd7-44ae-84c7-6f1fc8d8882b",
        productName: "헬스 회원권",
        defaultPrice: 480000,
        dagymPrice: 432000,
        dagymPriceRemainingCount: null,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스"],
      program: {
        free: "",
      },
      service: {
        free: "운동복 / 수건 / 양말 / / 샴푸 / 바디워시 / ️ 주차 2시간 가능",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: 1,
      isSportsFacilityCertified: true,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "68dde24e1c32ed2bfc873838",
      gymName: "광화문 턴온피트니스PT",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/acb05a17-7bca-446b-80f0-16cd13dd09c9/1759369935556_2e9d38a2-546f-4a59-895e-1e1edfee7cd3.jpg",
      address: "서울 종로구 청진동",
      location: [126.9804655, 37.5710334],
      review: {
        rate: 5,
        count: 1,
      },
      isWomenOnly: false,
      isReservationRequired: true,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "69cd1ea5-fdc8-439f-bb3e-80f20b45a892",
        productId: "9552b343-c098-480f-86e8-99e8a4b131ef",
        productName: "PT 회원권",
        defaultPrice: 4510000,
        dagymPrice: 4510000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "count",
        periodUnit: "week",
        period: 30,
        count: 50,
        productTags: [
          {
            id: "66ec10e09f965eebcf86ad65",
            name: "1:1P.T",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["1:1P.T"],
      program: {
        free: "",
      },
      service: {
        free: "무료주차 1시간",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "62c3eefd99269f001d846287",
      gymName: "시청 요가타운 서소문교육원",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/9c72d15d-edd0-4d7b-baac-4b98ab057641/bb04ce6ed28242f795798fd993ab7c8d.jpg",
      address: "서울 중구 서소문동",
      location: [126.9727451, 37.5630343],
      review: {
        rate: 5,
        count: 5,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "318442b5-b207-4abd-89dc-e8a534946763",
        productId: "77612695-a487-4e5e-9cd8-f029e2d23997",
        productName: "요가 (주 2회)",
        defaultPrice: 451000,
        dagymPrice: 451000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 4,
        count: null,
        productTags: [
          {
            id: "66ec10f39f965eebcf86ad73",
            name: "요가",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["요가", "P.T"],
      program: {
        free: "",
      },
      service: {
        free: "요가복 / 수건",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "63020a6a253e7e001dc8e1e0",
      gymName: "시청 겟투잇 피트니스",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/182bff8af4a1e60773/2WNeG7GivHCG1GcZv4bYV1mbQiYJStJv8KVD.background_photo.jpg",
      address: "서울 중구 순화동",
      location: [126.9712225, 37.5638223],
      review: {
        rate: 5,
        count: 9,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "37649422-16d4-4caf-95e4-18019353fdc9",
        productId: "c4ca5203-4ca3-4308-9545-aa335b2872b7",
        productName: "헬스 회원권(운동복+수건)",
        defaultPrice: 528000,
        dagymPrice: 522000,
        dagymPriceRemainingCount: null,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스"],
      program: {
        free: "",
      },
      service: {
        free: "️운동복+수건",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "5faa2611cf2a1a001d936319",
      gymName: "을지로 크로스핏 삼손",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/175b0a4b4fe567e322/2ZvGLVKhedgS5G7p2qJZRiJVMVz9VBikWjgb.background_photo.jpg",
      address: "서울 중구 장교동",
      location: [126.987052299704, 37.5671565387212],
      review: {
        rate: 5,
        count: 30,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "c350cc7c-7c22-4236-b435-a3c4f7faee0c",
        productId: "14fadf89-ee38-4f89-a802-3e2c6d9c6ff3",
        productName: "크로스핏  회원권",
        defaultPrice: 1200000,
        dagymPrice: 1200000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 6,
        count: null,
        productTags: [
          {
            id: "66ec12049f965eebcf86ada4",
            name: "크로스핏",
          },
          {
            id: "6a8807f3be49e96bcd0ff1a1",
            name: "하이록스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["크로스핏", "하이록스"],
      program: {
        free: "",
      },
      service: {
        free: "WI-FI / 수건 / 샤워용품 / 인바디",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "63bbc28a33db2b001d47b24e",
      gymName: "회현 더코어필라테스",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/185956fee3c5831ac4/2Y9jAKmjADGWv3vcCxPTQtFjUGWoTCyxD8ms.Big_231128_회현_더코어필라테스_34.jpg",
      address: "서울 중구 회현동1가",
      location: [126.980550175431, 37.55922913034157],
      review: {
        rate: 5,
        count: 2,
      },
      isWomenOnly: false,
      isReservationRequired: true,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "3f072d44-d396-42e2-a663-ca857f554ac8",
        productId: "20328beb-73b7-4e11-ac6d-cb4f9ea084fb",
        productName: "🙎🏼‍♀️여성전용🙎🏼‍♀️5:1그룹 필라테스 (주 2회)",
        defaultPrice: 2000000,
        dagymPrice: 1612800,
        dagymPriceRemainingCount: 1,
        productCategory: "general",
        productType: "count",
        periodUnit: "month",
        period: 12,
        count: 96,
        productTags: [],
      },
      exhibitionRemainingCount: null,
      tags: ["기구필라테스", "필라테스", "P.T"],
      program: {
        free: "",
      },
      service: {
        free: "️주차 2시간 가능 / ️수건 / 샤워실 / 락커",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "5fcd89cacf2a1a001d987efa",
      gymName: "광화문 MCT GYM",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1763ae23e593353c36/4K7ono7B2uMP7whX3mHCKxQHBxYWgsxNDv4ej85DzT8B.jpg",
      address: "서울 종로구 내수동",
      location: [126.9709930978744, 37.57260651126412],
      review: {
        rate: 5,
        count: 3,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "2db5cca5-c38f-4422-8665-f1b34da256f3",
        productId: "370a8978-9b48-4419-b881-f6d1bcd647b9",
        productName: "헬스",
        defaultPrice: 880000,
        dagymPrice: 880000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스", "P.T"],
      program: {
        free: "O.T (1회 50분)",
      },
      service: {
        free: "주차 (2시간) / WI-FI / 수건",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "6344f74658fe3f001d9a1f39",
      gymName: "서대문역 서대문주짓수",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/183c565e970530dc80/2WNFNwdj8neYzhMJHR7ya17d3FtGiPFuNWDY.Big_다운로드 (6).jpg",
      address: "서울 서대문구 충정로2가",
      location: [126.9659218788591, 37.56522419901734],
      review: {
        rate: 5,
        count: 6,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "b7bb8e0e-a5b6-41cb-acda-9bf4e4531624",
        productId: "623dc114-b349-4eb1-92c3-9070fba16b54",
        productName: "주짓수 회원권",
        defaultPrice: 840000,
        dagymPrice: 840000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 6,
        count: null,
        productTags: [
          {
            id: "66ec11af9f965eebcf86ad89",
            name: "주짓수",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["주짓수", "복싱", "P.T"],
      program: {
        free: "",
      },
      service: {
        free: "샤워실 / 락커 / Wi-fi",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "663ac385f09ceb001d683f79",
      gymName: "을지로 스트레칭조이",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/39458bc2-fe75-434d-ad2b-6e43a69dda71/1745483426439_b32ce906-8be4-46d9-9cfb-c64f7ab8e0d3.jpeg",
      address: "서울 중구 저동2가",
      location: [126.9905998853592, 37.56394257091787],
      review: {
        rate: 5,
        count: 3,
      },
      isWomenOnly: false,
      isReservationRequired: true,
      isLowestPrice: true,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "a97b9e0a-5f66-46c8-8e7f-b90bec70fdda",
        productId: "ea345f81-40c9-4dc4-a967-ea09acdb3af1",
        productName: "다짐전용6회권",
        defaultPrice: 168000,
        dagymPrice: 159600,
        dagymPriceRemainingCount: null,
        productCategory: "general",
        productType: "count",
        periodUnit: "month",
        period: 1,
        count: 6,
        productTags: [
          {
            id: "66ec163b9f965eebcf86adf1",
            name: "기타",
          },
          {
            id: "66ec11919f965eebcf86ad79",
            name: "매트필라테스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["스트레칭"],
      program: {
        free: "",
      },
      service: {
        free: "",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "695c5b8260c647607d6834ad",
      gymName: "서대문역 반반운동센터",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/19ceab46-daff-4ea9-b906-805caac3f0b1/1767612472665_f236822d-8775-4859-bfbf-1e4f7832e457.1767612466029",
      address: "서울 서대문구 충정로2가",
      location: [126.965325, 37.5660913],
      review: {
        rate: 0,
        count: 0,
      },
      isWomenOnly: false,
      isReservationRequired: true,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "8f374a16-89d7-4900-8997-ac7a75548309",
        productId: "fc22a576-54cd-498e-bed4-7e3964913c26",
        productName: "1:1 PT(재활/운동)",
        defaultPrice: 3060000,
        dagymPrice: 3060000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "count",
        periodUnit: "day",
        period: 200,
        count: 36,
        productTags: [
          {
            id: "66ec10e69f965eebcf86ad6b",
            name: "재활",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["1:1P.T"],
      program: {
        free: "상담권",
      },
      service: {
        free: "",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "695c5b7d41ef16c6a469b06d",
      gymName: "서대문역 더반골프라운지 프리미엄",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/7d7798a1-f704-4c01-857e-f26c9a07ad23/1767614602360_56cd2fbd-4cd7-4bc5-ad15-787e1c5457b1.1767614209170",
      address: "서울 서대문구 충정로2가",
      location: [126.965325, 37.5660913],
      review: {
        rate: 0,
        count: 0,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "e1cdbee6-b9f1-4982-a3db-1cdb10ca7760",
        productId: "ee063a34-a838-496d-9637-9d7e425a326e",
        productName: "라운지 이용권(타석 60분)",
        defaultPrice: 600000,
        dagymPrice: 600000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "count",
        periodUnit: "month",
        period: 12,
        count: 24,
        productTags: [
          {
            id: "66ec15569f965eebcf86adc8",
            name: "골프",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["골프"],
      program: {
        free: "첫 방문 체험 레슨(레슨비 무료, 시설 이용료 30,000원 발생)",
      },
      service: {
        free: "",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "67f35563be2740a6722f5e96",
      gymName: "독립문 이룸 기구 필라테스",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/4eba0bc9-2245-453b-ba63-fe26caa708ea/1743757037229_fbe7c3bd-9ccf-48b8-a287-f768b7cadf51.jpg",
      address: "서울 서대문구 옥천동",
      location: [126.962477, 37.5695495],
      review: {
        rate: 5,
        count: 2,
      },
      isWomenOnly: true,
      isReservationRequired: true,
      isLowestPrice: true,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "06a5f580-c4b5-48ff-ba7b-e7868c13fcd5",
        productId: "7847a943-9518-42e4-b1e1-1600aa986a4a",
        productName: "6:1 그룹 필라테스",
        defaultPrice: 830000,
        dagymPrice: 788500,
        dagymPriceRemainingCount: 1,
        productCategory: "general",
        productType: "count",
        periodUnit: "month",
        period: 9,
        count: 70,
        productTags: [
          {
            id: "66ec11939f965eebcf86ad7d",
            name: "기구필라테스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["필라테스"],
      program: {
        free: "",
      },
      service: {
        free: "",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "6639a931f09ceb001d67b62f",
      gymName: "무악 독립문 체육관",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18f513ce91510774ed/43BVNAkeTEipsUoPF2F95idzXBdUp64qmWjX.background_photo.jpg",
      address: "서울 종로구 무악동",
      location: [126.9591850830849, 37.5742612986031],
      review: {
        rate: 4.33,
        count: 3,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "bcb1d398-b928-43d6-b06d-cc2074453182",
        productId: "3c94383f-ff0f-416a-ba6d-05b5188aa02c",
        productName: "헬스 회원권",
        defaultPrice: 564000,
        dagymPrice: 564000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스"],
      program: {
        free: "",
      },
      service: {
        free: "️운동복+수건 / ️주차 2시간",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: 1,
      isSportsFacilityCertified: true,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "64422f458ec65b001d34507d",
      gymName: "후암 텐세그리티",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/187a288a71d526ed1f/2YUxpuEGZTUxX2hru6wCvddb4XNtczvcPkf9.background_photo.jpg",
      address: "서울 용산구 후암동",
      location: [126.9834922875075, 37.54886810307899],
      review: {
        rate: 0,
        count: 0,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: false,
      hasDailyItem: false,
      isLiked: false,
      price: {
        priceId: "b2d3f98a-d95b-4440-a117-d874bfba3c71",
        productId: "7e64483b-dfab-4d07-a3f8-42202fac1c4c",
        productName: "회원권",
        defaultPrice: 1200000,
        dagymPrice: 1200000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스", "P.T", "기구필라테스"],
      program: {
        free: "",
      },
      service: {
        free: "주차 1시간 무료",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: 1,
      isSportsFacilityCertified: true,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "599089bcb3d73d2cc88da985",
      gymName: "아현 247휘트니스&필라테스",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/de15daad-f398-4a1b-a991-5a944be49e9a/1744793183359_bf73c3bd-4f7f-4439-821d-768a33e92817.jpg",
      address: "서울 서대문구 북아현동",
      location: [126.957526, 37.557779],
      review: {
        rate: 4.9,
        count: 99,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "65b0ef62-669e-4681-9ba9-7f08b328cd85",
        productId: "8ca6d6bd-a972-4e77-af93-cd2972ee7101",
        productName: "8:1 기구 필라테스",
        defaultPrice: 770000,
        dagymPrice: 693000,
        dagymPriceRemainingCount: 4,
        productCategory: "general",
        productType: "count",
        periodUnit: "month",
        period: 10,
        count: 80,
        productTags: [
          {
            id: "66ec11939f965eebcf86ad7d",
            name: "기구필라테스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스", "기구필라테스"],
      program: {
        free: "",
      },
      service: {
        free: "️수건 / ️Wi-Fi / ️샤워실 / ️반신욕기 이용",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: 1,
      isSportsFacilityCertified: true,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "6a19193fe8b4d7d0edfd2e15",
      gymName: "연건 MCTGYM",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://dgmanager.s3.ap-northeast-2.amazonaws.com/thumbnail/gym-photo/d6f40bdb-edd9-480d-91b5-9c026f841295/1787569471480_eda5863e-5768-41f1-a315-dd97de4fa9b2.jpeg",
      address: "서울 종로구 연건동",
      location: [127.0000642, 37.5762586],
      review: {
        rate: 4,
        count: 1,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "04f5c962-8a15-4b38-9db8-f5bc4bb58a5a",
        productId: "813590e8-4b5a-4ed0-b928-c9e286b8976f",
        productName: "헬스 회원권(가입비 및 VAT포함)",
        defaultPrice: 495000,
        dagymPrice: 495000,
        dagymPriceRemainingCount: 0,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스"],
      program: {
        free: "",
      },
      service: {
        free: "",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "64b7090ce53cb5001dd7ba78",
      gymName: "공덕 헤이점핑",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1896afb5a7315e672d/2WNK7jMd1s1AWro9ktV2P4kqWT8Pszr5X73V.센터 Big 복사.jpg",
      address: "서울 마포구 공덕동",
      location: [126.9624342, 37.5512149],
      review: {
        rate: 4.9,
        count: 10,
      },
      isWomenOnly: false,
      isReservationRequired: true,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "55f49174-22e3-40bd-b6b0-658bb8619513",
        productId: "9e556da5-1bf6-4c1b-96a0-f23c4cd78158",
        productName: "기간 이용권",
        defaultPrice: 1728000,
        dagymPrice: 1428000,
        dagymPriceRemainingCount: 1,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: null,
        productTags: [
          {
            id: "66ec14649f965eebcf86adbb",
            name: "점핑운동",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["점핑운동"],
      program: {
        free: "",
      },
      service: {
        free: "신발보관 / 프로틴쉐이크제공 / ",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: null,
      isSportsFacilityCertified: false,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
    {
      _id: "5b6c6c20729a8461514bea7c",
      gymName: "애오개 헬스존",
      gymPhotoBig: null,
      gymPhotoSmall:
        "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1651f865fbf5da8d11/2ZxGa4f51HCSx98gw3qmUsmHWdyDiSGrTj6Q.Big_231212_애오개_헬스존_07.jpg",
      address: "서울 마포구 공덕동",
      location: [126.960333, 37.550072],
      review: {
        rate: 4.88,
        count: 24,
      },
      isWomenOnly: false,
      isReservationRequired: false,
      isLowestPrice: true,
      hasDailyItem: true,
      isLiked: false,
      price: {
        priceId: "ecabd74e-404f-4edc-819e-8fe64174240b",
        productId: "feaca7b3-c630-46c0-bc8d-b10ff5303a44",
        productName: "헬스이용권",
        defaultPrice: 400000,
        dagymPrice: 380000,
        dagymPriceRemainingCount: 4,
        productCategory: "general",
        productType: "period",
        periodUnit: "month",
        period: 12,
        count: 365,
        productTags: [
          {
            id: "66ec10269f965eebcf86ad5e",
            name: "헬스",
          },
        ],
      },
      exhibitionRemainingCount: null,
      tags: ["헬스", "P.T"],
      program: {
        free: "",
      },
      service: {
        free: "️주차 3시간 / ️수건 + 탈의실 락커",
      },
      label: null,
      videoUrl: null,
      videoThumbnailUrl: null,
      coupons: null,
      culturalTaxDeductionRate: 1,
      isSportsFacilityCertified: true,
      isDagymRecommended: false,
      hasActiveHotDeal: false,
      matchedBy: null,
      matchedData: null,
      searchScore: null,
    },
  ],
};

const wowo = data.centerList.map((x) => {
  if (x.isWomenOnly == true) {
    return x;
  }
});

console.log(wowo);

const pprice = data.centerList.map((x) => {
  if (x.price.defaultPrice >= 3000000) {
    return x;
  }
});

console.log(pprice);

const parking = data.centerList.map((x) => {
  if (x.service.free.includes("무료")) {
    return x;
  }
});

console.log(parking);
